[package]
name = "tc_kimlik"
version = "0.2.0"
authors = ["Hakan ERSU <hakanersu@gmail.com>"]
edition = "2018"
description = "Turkish identifacation number validator and generator."
license = "MIT"

[dependencies]
rand = "0.7"