[package]
name = "tc_kimlik"
version = "0.1.0"
authors = ["Hakan ERSU <hakanersu@gmail.com>"]
edition = "2018"
description = "Turkish identifacation number validation and tools."
license = "MIT"

[dependencies]
rand = "0.7"